### PR TITLE
OTC-780: fix calculation of used service or item

### PR DESCRIPTION
**Pull request by jdolkowski**
https://openimis.atlassian.net/browse/OTC-780

Now it is calculated by summing all the chosen items or services from all claims assigned to insuree.

It is a part of frontend PR: https://github.com/openimis/openimis-fe-policy_js/pull/28

### CODE REVIEW

**Comment by delcroip** [comment]
please check the CI

**Comment by jdolkowski** [comment]
> For now I am moving this ticket to need more clarification and turning the PR to draft. I need to check the way how the quantity should be calculated to see if the problem is tests or my approach.

**Comment by jdolkowski** [comment]
@delcroip For now I am moving this ticket to need more clarification and closing the PR. I need to check the way how the quantity should be calculated to see if the problem is tests or my approach.

**Comment by jdolkowski** [comment]
This PR fixes tests: https://github.com/openimis/database_ms_sqlserver/pull/160

**Review by dragos-dobre — APPROVED** [review]

**Review by dborowiecki — APPROVED** [review]

**Pull request merged**
